tab-width: 4
use-tabs: false
print-width: 120
double-quotes: false
trailing-commas: es5
semicolons: true
arrow-parens: always
bracket-spacing: true
indent-script-and-style: false
finder:
  exclude:
    - modules
    - node_modules
    - storage
    - vendor
  name: "*.vue"
#vue:
#  tab-width: 4
#  use-tabs: false
#  print-width: 120
#  double-quotes: false
#  trailing-commas: es5
#  semicolons: true
#  arrow-parens: always
#  bracket-spacing: true
#  indent-script-and-style: false
#  finder:
#    exclude:
#      - modules
#      - node_modules
#      - storage
#      - vendor
#    name: "*.vue"
#
#css:
#  tab-width: 4
#  use-tabs: false
#  print-width: 120
#  double-quotes: false
#  finder:
#    exclude:
#      - modules
#      - node_modules
#      - storage
#      - vendor
#    name:
#      - "*.css"
#      - "*.scss"
#      - "*.less"
#js:
#  tab-width: 4
#  use-tabs: false
#  print-width: 120
#  double-quotes: false
#  trailing-commas: es5
#  semicolons: true
#  arrow-parens: always
#  bracket-spacing: true
#  finder:
#    exclude:
#      - modules
#      - node_modules
#      - storage
#      - vendor
#    name:
#      - "*.js"
#      - "*.jsx"
#    not-name:
#      - "*.min.js"
