name: Deploy To Firebase
on:
  push:
    branches:
      - stage
  repository_dispatch:
    types: [stage-command]
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run generate
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:droidcon2020
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


      - name: Comment on success
        if: success() && github.event_name == 'repository_dispatch'
        uses: peter-evans/create-or-update-comment@v1.4.1
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction: hooray
          body: |
            Successfully deployed [PR-${{ github.event.client_payload.pull_request.number }}](See https://github.com/${{ github.repository}}/actions/runs/${{ github.run_id }}) to [staging](https://droidcon2020.web.app)

      - name: Comment on failure
        if: failure() && github.event_name == 'repository_dispatch'
        uses: peter-evans/create-or-update-comment@v1.4.1
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction: eyes, confused
          body: |
            Failed to deploy #${{ github.event.client_payload.pull_request.number }} to staging
            See https://github.com/${{ github.repository}}/actions/runs/${{ github.run_id }}
