name: Build and Deploy
on:
  push:
    branches:
      - stage
  repository_dispatch:
    types: [stage-command]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run generate
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Update deployment status (success)
        if: success() && github.event_name == 'pull_request'
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: ${{ https://droidcon2020.web.app }}
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Comment on success
        if: success()
        uses: peter-evans/create-or-update-comment@v1.4.1
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction: hooray
          body: |
            Successfully deployed [PR-${{ github.event.client_payload.pull_request.number }}](See https://github.com/${{ github.repository}}/actions/runs/${{ github.run_id }}) to [staging](${{ https://droidcon2020.web.app }})

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Comment on failure
        if: failure()
        uses: peter-evans/create-or-update-comment@v1.4.1
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction: eyes, confused
          body: |
            Failed to deploy #${{ github.event.client_payload.pull_request.number }} to staging
            See https://github.com/${{ github.repository}}/actions/runs/${{ github.run_id }}
